### ISSUE TITLE
Broken link to indexes

### ISSUE THREAD

**Issue by amjedbj** [eXascaleInfolab/TRank#3]
Hi, 

Link to Lucene indexes in README is broken. Could you please update [README.md](https://github.com/eXascaleInfolab/TRank/blob/master/README.md) file  with the correct URL?

> TRank requires 3 Lucene indexes that are available for [download here](http://ftp.exascale.info/sites/default/files/uploaded/trank/trank-indexes.tgz). 

Thank you! @pcudre @pirroh @dragoon

**Comment by albertotonon** [comment]
fixed. If you're interested there is also an online version of TRank at http://trank.exascale.info.

Cheers, 


Alberto

**Comment by amjedbj** [comment]
Yep, I have already submited some tweets to your API. 
Thank you for sharing your source code @albertotonon  :)

Regards,
Lamjed
